### PR TITLE
To variables

### PR DESCRIPTION
**Pull request by ynixon**
changed hardcoded data to variables

### CODE REVIEW

**Comment by lioramilbaum** [comment]
Is fixing logic of dump and load related to this PR?

**Comment by ynixon** [comment]
No, I don't know why we see "fixed logic of dump and load checks 0038093"
Don't know how to eliminate this
by this PR is only change to variables

**Comment by lioramilbaum** [comment]
update your fork master from upstream
checkout your branch
rebase master
cleanup the code

**Comment by lioramilbaum** [comment]
something went wrong with your commits. Start over with a new branch/new PR.

**Comment by ynixon** [comment]
it looks good and works 
What is the problem?

**Comment by lioramilbaum** [comment]
I forgot to refresh the PR page :-)

**Pull request merged**
