### PR TITLE
replaces bootstrap-infra from bash to ansible playbook

### PR DESCRIPTION
**Pull request by ynixon**
#144 
1. Added a playbook for the infra stage (currently docker)
2. Deleted the bash version of the infra stage
3. Added to .ignore intermediate ansible files (*.retry)
4. Added a script for use withing travis to check if you have CRLF (windows style) files.

all was verified

### CODE REVIEW

**Comment by ynixon** [comment]
checked the install also on stage (aws)

**Comment by lioramilbaum** [comment]
squash your commits to one

**Comment by lioramilbaum** [comment]
what if ansible is not installed? or maybe the user should be in a virtualenv? which ansible version are we working with?

a wrapper script should take of all those questions

**Comment by lioramilbaum** [comment]
STAGE and PROD environment are based on python 3.6. Isn't it?

**Comment by lioramilbaum** [comment]
@ynixon I am approving the PR even thought not all review comments were address. We will address them in the future.

**Pull request merged**
