### PR TITLE
#Issue 326 | Embed app architecture in app homepage

### LINKED ISSUE #326: Embed Architecture diagram in app
Now that we have a new Architecture document, it should be embedded in the app to enhance its accessibility
The diagram can be found here 
https://www.lucidchart.com/invitations/accept/c25b7de6-9321-4e16-afb1-2a586e78e188

### PR DESCRIPTION
**Pull request by leonicus**
Fixes #326

### CODE REVIEW

**Comment by leonicus** [comment]
@lioramilbaum I thought it was better since we edit it there, then it would get updated automatically. Was it a momentary outage? Its working for me....anyhow, if you prefer to download the html locally I'll do it...

**Comment by lioramilbaum** [comment]
@leonicus Good point. In that case we should handle the case, lucidchart is not available

**Comment by lioramilbaum** [comment]
@Balex3000 Can you provide feedback to the position? Is it the right place to position the diagram?

**Comment by lioramilbaum** [comment]
@leonicus another option is to implement a service which updates the diagram every time there is a change.

**Comment by leonicus** [comment]
@lioramilbaum Well, Lucidchart don't have a way to subscribe to events, so it would require a lot of logic  on our part to compare and decide when to change. I think the way I implemented it now is not ideal but we can live with it - 
The application tries to download the file from lucidchart and save it locally. If it's unsuccessful, the last downloaded file remains and will be displayed

**Pull request merged**
