### PR TITLE
Moving from docker to docker-compose

### PR DESCRIPTION
**Pull request by vadimsh**
Vagrantfile:

"dcompose" script added
docker section removed except docker install and devopsloft_network create
added this shell command to remove Ubuntu locks: "kill $(pgrep 'unattended')" and placed before "apt-get update"
Docker-compose.yml :
devopsloft_network commented out but can be added back if needed

### CODE REVIEW

**Comment by ynixon** [comment]
When using docker-compose, must we define a network?

**Comment by ShimiTaNaka** [comment]
@ynixon no, compose will do it for you if you don't se it up yourself

**Comment by ynixon** [comment]
Good. 
Currently, when we run "vagrant up - -provision" twice. 
We get error because of the existence of the network. 
If we omit the explicit definition of network, we will solve this problem.

**Comment by ShimiTaNaka** [comment]
If you are referring to https://github.com/devopsloft/devopsloft/pull/216/files#diff-23b6f443c01ea2efcb4f36eedfea9089R156
Then you are correct, it's fully redundant

**Comment by vadimsh** [comment]
Vault container added to docker-compose.yaml

**Pull request merged**
