### PR TITLE
prevent duplicate subscribers

### PR DESCRIPTION
**Pull request by lioramilbaum**
#173

### CODE REVIEW

**Comment by ynixon** [comment]
Using Hebrew parameters in the sign up got the following error in the web interface !!

> MySQLdb._exceptions.OperationalError
> MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xD7\\x99\\xD7\\x95\\xD7\\xA1...' for column 'name' at row 1")
> 
> Traceback (most recent call last)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
> return self.wsgi_app(environ, start_response)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
> response = self.handle_exception(e)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
> reraise(exc_type, exc_value, tb)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> raise value
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> response = self.full_dispatch_request()
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/vagrant/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> raise value
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> rv = self.dispatch_request()
> File "/vagrant/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/vagrant/application.py", line 62, in signup
> VALUES(%s, %s, %s, %s)", (name, email, username, password))
> File "/vagrant/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
> res = self._query(query)
> File "/vagrant/venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 312, in _query
> db.query(q)
> File "/vagrant/venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 224, in query
> _mysql.connection.query(self, query)
> MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xD7\\x99\\xD7\\x95\\xD7\\xA1...' for column 'name' at row 1")
> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
> To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.
> 
> You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
> 
> dump() shows all variables in the frame
> dump(obj) dumps all that's known about the object
>

**Comment by lioramilbaum** [comment]
I will need to add code which validates the values are in English.

**Comment by lioramilbaum** [comment]
@ynixon fixed the Hebrew issue.

**Comment by ynixon** [comment]
I checked it again and now, it works fine

**Pull request merged**
