### PR TITLE
Web ui

### PR DESCRIPTION
**Pull request by leonicus**
Fix of issue #298 - Change "contact us" content to "under construction"

### CODE REVIEW

**Comment by leonicus** [comment]
@lioramilbaum failures re not related to this PR. See https://github.com/devopsloft/devopsloft/issues/316

**Comment by lioramilbaum** [comment]
Please provide more information what this PR is addressing

**Comment by lioramilbaum** [comment]
@leonicus Pull the latest changes and rebase. Verify the CI is passing.

**Comment by lioramilbaum** [comment]
Why this PR includes files from the previous PR? I have reason to believe you have used the wrong git flow.

**Comment by leonicus** [comment]
@lioramilbaum I think I finally did a correct rebase :)

**Comment by lioramilbaum** [comment]
Again, you are using the wrong git/github workflow. The file which fixes the spinning should not be part of your PR.
Do you want me to cover it tomorrow?

**Comment by leonicus** [comment]
@lioramilbaum Yes, I noticed. I don't know why, I used same flow that previously worked...git fetch + rebase and then push. If we get to it tomorrow it would be great

**Comment by lioramilbaum** [comment]
Should I review this PR? If yes, please Re-request a review.

**Comment by leonicus** [comment]
After discussing with @lioramilbaum, we agreed this issue is no longer relevant to the current stage of the app. Closing, the issue can be closed as well

**Pull request closed without merging**
