### PR TITLE
Added docker service to vagrantfile

### PR DESCRIPTION
**Pull request by ynixon**
Issue #137 Added file bootstrap-infra.sh to install docker at the first stage in the vagrant file

### CODE REVIEW

**Comment by Balex3000** [comment]
DO NOT MERGE YET
Yossi will push slimmer version of the bootstrap-infra.sh file

**Comment by lioramilbaum** [comment]
The change is currently not supported in PROD environment. Should be handled after PR #139 is merged.

**Comment by lioramilbaum** [comment]
@Balex3000 and @noamgu please test the PR in DEV and STAGE environments before approving/merging the PR

**Comment by Balex3000** [comment]
This is already replaced by PR #145

**Pull request closed without merging**
