### PR TITLE
Moved all instillation to Ansible and Ansible galaxy

### PR DESCRIPTION
**Pull request by ynixon**
#97 #98 #99

### CODE REVIEW

**Comment by ynixon** [comment]
was checked on dev + stage

**Comment by lioramilbaum** [comment]
when spinning dev environment on OSX hitting an error:
`
TASK [start application in background] *****************************************
fatal: [dev]: FAILED! => {"changed": true, "cmd": "/vagrant/startup.sh", "delta": "0:00:00.002723", "end": "2019-03-02 07:24:15.820466", "msg": "non-zero return code", "rc": 126, "start": "2019-03-02 07:24:15.817743", "stderr": "/bin/sh: 1: /vagrant/startup.sh: Permission denied", "stderr_lines": ["/bin/sh: 1: /vagrant/startup.sh: Permission denied"], "stdout": "", "stdout_lines": []}`

**Comment by lioramilbaum** [comment]
you need to add executable permissions to startup.sh file

**Comment by ynixon** [comment]
I though this was the problem.

**Comment by ynixon** [comment]
I checked before the change and had the same error
After the change, it seems that everything works 
(I assume this was a windows problem -> not able to commit permissions properly)

**Pull request merged**
