### PR TITLE
issue#44 - Add Contact Us page template and links from home page

### PR DESCRIPTION
**Pull request by noamhasingit**
issue#44 - Add Contact Us page template and links from home page

### CODE REVIEW

**Comment by lioramilbaum** [comment]
@noamhasingit The Travis CI build failed. Can you check it out and see why?

**Comment by noamhasingit** [comment]
HI Liora, 

The problem was with pip8 , it is failling on 1 back instead of 2 between classes.  I commit my fix  and verified that the new fix works in pip8 online editor.

**Comment by noamhasingit** [comment]
Fixed:  expected two blank lines pep8 warning in python
<https://stackoverflow.com/questions/33466860/expected-two-blank-lines-pep8-warning-in-python>

**Comment by lioramilbaum** [comment]
Where is the fix commit? It should be linked to the PR. The Travis CI build still shows a failure. 
https://travis-ci.org/DevOpsLoft/DevOpsLoft/builds/377452659?utm_source=github_status&utm_medium=notification
Something related to python version.

**Comment by noamhasingit** [comment]
i added it to my fork. do i need to open another pull request? can i push
it to the main branch. sorry im not practiced in git...

**Comment by lioramilbaum** [comment]
GitHub should have picked it up as soon as you committed to your local repo. Verify that the commit was performed and  assigned to issue #44

**Comment by noamhasingit** [comment]
I pushed the fix, it looks ok. I also restarted travis build and it passed.
Let me know if I have amissed something.

**Pull request merged**
