### PR TITLE
Optimizing spin.py to spin dev env in Windows host

### PR DESCRIPTION
**Pull request by hilsenrat**
Technical debt:

- box_prune is commented out

### CODE REVIEW

**Comment by lioramilbaum** [comment]
@hilsenrat The CI is breaking. I know @noamhasingit is trying to address it. Can you figure out the root cause of the failure?

**Comment by lioramilbaum** [comment]
@hilsenrat I have merged @noamhasingit 's PR first. Now there is a merge conflict. Can you please rebase and resolve it. I want to merge your PR and fix the failing CI today.

**Comment by noamhasingit** [comment]
I have added some comments but I can not merge it don't have permissions.

**Comment by lioramilbaum** [comment]
@noamhasingit I am not following. What are you trying to merge?

**Comment by lioramilbaum** [comment]
@hilsenrat Please go over the PR and verify it is aligned with our new direction with Docker.

**Pull request closed without merging**
