### PR TITLE
Fix cleanup instructions

### PR DESCRIPTION
**Pull request by bregman-arie**

### CODE REVIEW

**Comment by bregman-arie** [comment]
@lioramilbaum

**Comment by bregman-arie** [comment]
You are saying the commands are wrong? There are missing commands? They don't work? Can you please elaborate on what is the problem

**Comment by lioramilbaum** [comment]
There is an instruction missing which used to be there. There is a script which tears down the environment.

**Comment by leonicus** [comment]
@bregman-arie for dev environment, before removing spincontainer, we should run a script from within spincontainer to cleanup the environment.
The command from within the container was (in /home);
`python spin-docker.py --action destroy`

**Pull request merged**
