### PR TITLE
favicon

### PR DESCRIPTION
**Pull request by lioramilbaum**
https://stackoverflow.com/questions/4888377/how-to-add-a-browser-tab-icon-favicon-for-a-website

### CODE REVIEW

**Comment by lioramilbaum** [comment]
@noamgu the service you suggested generates icon with white background. Is there a way to make it transparent?

**Comment by noamgu** [comment]
This one worked out for me
www.favicomatic.com

**Comment by lioramilbaum** [comment]
@noamgu the second one worked

**Comment by lioramilbaum** [comment]
@noamgu Are we ready to merge this PR? Again, if you have styling comments, I would suggest you take it from here. I don't have the touch for frontend like you do.

**Pull request merged**
