### PR TITLE
added travis test for empty users table

### PR DESCRIPTION
**Pull request by ynixon**
Added a code to check that users table is empty
Using the same yaml variables of the mysql installation (in the Ansbile vars)  
Implicit it is checking that the mysql is working properly.
Checked and tried with exit status <> 0, and it was broken.

### CODE REVIEW

**Comment by lioramilbaum** [comment]
You have used a different mysql python module than the one used in the app.  For consistency, we should use the same. Switch the one in the test or in the app.

**Comment by ynixon** [comment]
I did not find a way to test pure mysql test (without the web interface) using flask_mysqldb
And I am sure the other way around is not feasible.

**Comment by lioramilbaum** [comment]
@ynixon Can you give me an example, because I am not following.

**Comment by ynixon** [comment]
code
```#!/usr/bin/env python
import yaml
from flask import Flask
from flask_mysqldb import MySQL


def load_config(config_file):
    with open(config_file, 'r') as stream:
        try:
            return yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)


my_config = load_config('provisioning/playbooks/group_vars/all.yml')

is_table_empty = Flask(__name__)

# Config MySQL
is_table_empty.config['MYSQL_HOST'] = my_config['mysql_bind_address']
is_table_empty.config['MYSQL_USER'] = my_config['mysql_root_username']
is_table_empty.config['MYSQL_PASSWORD'] = my_config['mysql_root_password']
is_table_empty.config['MYSQL_DB'] = 'devopsloft'
is_table_empty.config['MYSQL_CURSORCLASS'] = 'DictCursor'
# Init MySQL

mysql = MySQL(is_table_empty)


def is_table_empty(table):

    cursor = mysql.connection.cursor()
    query = ("SELECT COUNT(*) FROM %s" % table)
    cursor.execute(query, ())

    row_count = cursor.fetchone()[0]
    print("number of rows in {}: {}".format(table, row_count))
    exit(row_count)

    cursor.close()


if __name__ == "__main__":
    is_table_empty("users")
```
output
```
(venv) root@ubuntu-bionic:/vagrant# python3 tests/is_table_empty.py
Traceback (most recent call last):
  File "tests/is_table_empty.py", line 44, in <module>
    is_table_empty("users")
  File "tests/is_table_empty.py", line 32, in is_table_empty
    cur = mysql.connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by lioramilbaum** [comment]
ohhh.... got it. 'mysql' gets value as a flask app.

**Pull request merged**
