### PR TITLE
Fixes #129 - Break the code to docker-compose

### LINKED ISSUE #129: [Breaking Down the Monolith] Deloy process using docker-compose
Epic #123

### PR DESCRIPTION
**Pull request by ShimiTaNaka**
Also handles #128 #127 #126 #125 #124

### CODE REVIEW

**Comment by lioramilbaum** [comment]
docker-compse should be used inside the VM vagrant spins with VirtualBox.

**Comment by ShimiTaNaka** [comment]
disagree, there is no real need to have the docker-compose in the VM, it's redundant specially since there is not host-mapping volumes. All you need to do is set `DOCKER_HOST` env variable to point it to the VM and control it remotely.
Yes, it does mean you need to expose the docker outside, running it from inside the VM just complicates stuff.
You can also look at `docker-machine` which does exactly that.

**Comment by lioramilbaum** [comment]
We are still working with a VM in stage and prod. This is not about to change soon. Having said that, we will continue working with a similar architecture in dev.

**Comment by ShimiTaNaka** [comment]
That doesn't mean that the compose needs to run from inside the VM.
The lifecycle and dev flow if it's inside a VM only gets more complicated

**Comment by lioramilbaum** [comment]
What about the installations/configurations we do in the VM which are not happening in the containers?
Do we really want to take the dev env deployment to a different direction than the stage+prod env deployments?

**Comment by ShimiTaNaka** [comment]
Yes.
In dev you don't want to always build the image on every single change, it's redundant and prolongs the lifecycle of the development, you want the change to be instant, so you map the code inside and only re-build if there are changes in the `requirements.txt`, in prod you want to have the code in the container, you technically can put it on the VM and map it inside, but it's redundant and doesn't fit best-practices to my knowledge.
The docker-compose also allows *not* using a VM, if we don't want to, on OSx there is no real need to setup vagrant, nor on Linux machines

**Comment by lioramilbaum** [comment]
Is it really necessary in the current  solution to rebuild the image on every change? Isn't the mount of /vagrant to project directory enables just that? And if it isn't, can we address it to support this option on top of what we have today?
We can always keep the current solution working and support spinning a dev environment which is stripped from the VM. Not sure, it is a good idea to drop the VM spinning entirely.
Keep in mind that each lofter has a his own laptop. Having said that, the dev environment spinning should support commonly used OSs.

**Comment by ShimiTaNaka** [comment]
As said, rebuilding after every change is wrong, I will amend the PR to handle that.
All I am saying is that when moving to docker, there is no real need to have anything on the VM aside from just Docker, Running the compose from outside allows better integration also with IDEs which support it (i.e IntelliJ)
What I'm asking is basically, why do we need to run docker-compose from inside the VM rather than outside it? (even if we sill use a VM)

**Comment by lioramilbaum** [comment]
I am not sure I agree with you as long as our AWS environment do have encapsulated VMs.
Every new option should not break what works now, till it is proven useless for the most common workflows.

**Comment by ShimiTaNaka** [comment]
The environment is still encapsulated, that doesn't change, only the code is pre-baked into the docker (in production) and not in the VM.
I can change it, sure, it's just far less convenient to work with since you always need to switch between the laptop and the VM, plus, again, it will enforce also non-windows to install Vagrant whereas it can be an optional step

**Comment by lioramilbaum** [comment]
In that case, do provide the option to spin the dev environment with or without the VM.

**Comment by ShimiTaNaka** [comment]
@lioramilbaum Care to look at it?
Though I would be happy if others would look at it as well to get more questions and opinions (the more the merrier)

**Comment by ShimiTaNaka** [comment]
@lioramilbaum what do we want to do with this PR?

**Pull request closed without merging**
