### PR TITLE
Improving CI

### PR DESCRIPTION
**Pull request by lioramilbaum**

### CODE REVIEW

**Comment by ynixon** [comment]
Are you going to add Activation of install commands in Travis

**Comment by lioramilbaum** [comment]
I am not following. What are the activation of install commands?

**Comment by ynixon** [comment]
ok, you already did it - the Ansible command - cool

**Comment by lioramilbaum** [comment]
I want to kick my experience with Travis cause I am going to cover this topic in the coming workshop

**Pull request merged**
