### PR TITLE
vault persistent storage

### PR DESCRIPTION
**Pull request by lioramilbaum**

### CODE REVIEW

**Comment by ShimiTaNaka** [comment]
Not sure I understand all the commits here.
Possibly the change is more than just replacing the backend of vault?

**Comment by lioramilbaum** [comment]
@ShimiTaNaka It was more about enabling data persistency

**Comment by ShimiTaNaka** [comment]
Then what are the changes to the application code?

**Comment by lioramilbaum** [comment]
To use different storage backends in the various environments:
dev/ci -> file
stage/prod -> s3

**Comment by ShimiTaNaka** [comment]
Still not sure I understand, I lack the full flow of the things.
Changing the backend of vault shouldn't affect anything in the application itself, this is part of the idea to externalise configuration

**Comment by lioramilbaum** [comment]
@ShimiTaNaka I get what you are saying. Will work on it.

**Comment by lioramilbaum** [comment]
@ShimiTaNaka Addressed the issue you raised. Have a look.

**Comment by ShimiTaNaka** [comment]
@lioramilbaum I still not fully understand the PR.
Looking at it as is, I don't understand how some of the changes are related, for example
https://github.com/devopsloft/devopsloft/pull/269/files#diff-944dab53fc42b7be678fecb3d7fdb2bfR14
or https://github.com/devopsloft/devopsloft/pull/269/files#diff-944dab53fc42b7be678fecb3d7fdb2bfR47 and there are more.
Either there are more changes here than simply switch the backend, or I am missing context using multiple commits with descriptive comment

**Comment by lioramilbaum** [comment]
@ShimiTaNaka Yes. I have included several efforts in one PR. Let me break it to small PRs. One effort per PR.

**Comment by lioramilbaum** [comment]
@ShimiTaNaka  This is the first PR of multiple PRs.

**Pull request merged**
